name: 'build & test'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
    - '**Dockerfile'
    - '**.json'
    - '**.cs'
    - '**.csproj'
    - '**.sln'

env:
  DOTNET_VERSION: '8.0.x' # SDK version

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
